### ISSUE TITLE
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'to_string'

### ISSUE THREAD

**Issue by shaniAmare** [zsolt-balazs/LoRTIA#1]
Hi @zsolt-balazs ,

I'm keen to try out this tool. However, when I use it on a `.sam` file of PacBio HiFi reads generated from the `ccs.fastq` files, I get the following error.

```
Sorting /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/lortia_output_merged/S4R_m64087_200413_100303.ccs.sam...
Iterating over /stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/lortia_output_merged/S4R_m64087_200413_100303.ccs.sam...
Traceback (most recent call last):
  File "./LoRTIA", line 309, in <module>
    Samprocessor.Samprocessor(args)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LoRTIA/LoRTIA/Samprocessor.py", line 655, in Samprocessor
    sam_iterator(args)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LoRTIA/LoRTIA/Samprocessor.py", line 609, in sam_iterator
    tsr5_dict)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LoRTIA/LoRTIA/Samprocessor.py", line 548, in deal_with_same_name
    tsr5_dict)
  File "/stornext/General/data/user_managed/grpu_mritchie_1/Shani/long_read_benchmark/LoRTIA/LoRTIA/Samprocessor.py", line 490, in prepare_new_sam_line
    readline = read.to_string()
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'to_string'
```

Not sure why this error is happening. I used the following to map the `ccs.fastq` reads through minimap:
`minimap2 -ax splice:hq -uf -Y ${REF} ${FASTQ} > ${OUT_DIR}/${OUT_P}.sam;
`

My script to run Lortia was (calling within the installed directory; reading the ` .sam` file from the `$OUT_DIR` and writing the LoRTIA results back to `$OUT_DIR` as well):
```
./LoRTIA \
-5 AGAGTACATGGG \
--five_score 16 \
--check_in_soft 15 \
-3 AAAAAAAAAAAAAAA \
--three_score 18 \
-s poisson \
-f True \
${OUT_DIR}/${OUT_P}.sam \
${OUT_DIR} \
${REF}
```
I might be doing something very naive. So your feedback will be highly appreciated!

Shani.

**Comment by zsolt-balazs** [comment]
Hi Shani!

Thank you for your interest in the software.
Are you using pysam version 0.15?
Before version 0.14.0, the function to_string was called tostring... maybe that is the problem. Otherwise I don't see anything that you would be doing wrong.

Best wishes,

Zsolt
