### ISSUE TITLE
gff_creator typeError

### ISSUE THREAD

**Issue by mei-du** [zsolt-balazs/LoRTIA#4]
Hi!
I was able to run LoRTIA on my sample .sam files separately but I have been receiving this error when trying to run on merged multiple sample .sam files. Is it something to do with the contig column in the intron.tsv file and/or something from the merging process? Thanks

```
samtools view -H ${DIR}/1R_ccs_minimap_aligned.sam > ${DIR}/header_A.sam
samtools merge -h header_A.sam merged_A.sam 1R_ccs_minimap_aligned.sam 2R_ccs_minimap_aligned.sam 3R_ccs_minimap_aligned.sam
```
```
./LoRTIA \
-5 AGAGTACATGGG \
--five_score 16 \
--check_in_soft 15 \
-3 AAAAAAAAAAAAAAA \
--three_score 18 \
-s poisson \
-f True \
${BAM_DIR}/${FILE} \
${OUT_DIR} \
${REF}
```
```
Creating intron gff file...
Traceback (most recent call last):
  File "./LoRTIA", line 347, in <module>
    Gff_creator.Gff_creator(args)
  File "/redacted/path/to/file/Gff_creator.py", line 87, in Gff_creator
    new_df = new_df.sort_values(by=['contig'])
  File "/home/users/allstaff/du.m/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 5308, in sort_values
    k, kind=kind, ascending=ascending, na_position=na_position, key=key
  File "/home/users/allstaff/du.m/.local/lib/python3.7/site-packages/pandas/core/sorting.py", line 301, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by zsolt-balazs** [comment]
Hm... Thank you for raising this issue. I am almost sure that the problem is that some contigs are understood as integers (1, 2, 3, 4, etc.) while some are understood as strings (chr1, chr2, chr3, chr4, etc.). I will fix this issue soon. As a temporary workaround I could recommend you rename your contigs to either be all strings, that would mean renaming chromosomes that are only named like 1 to chr1. 
I don't think it has anything to do with the merging process, so you can go on working with such merged files if you want to.
